import { SLASH_COMMANDS } from "./slash-commands";

export type CommandCategory = "general" | "info" | "leveling" | "moderation";
export interface CommandDefinition {
  name: string;
  category: CommandCategory;
  description: string;
  supported: boolean;
}

export const COMMAND_CATALOG: CommandDefinition[] = [
  { name: "daily", category: "general", description: "استلم مكافأة Glow Coin اليومية", supported: true },
  { name: "balance", category: "general", description: "اعرض رصيدك من عملة Glow Coin", supported: true },
  { name: "transfer", category: "general", description: "تحويل Glow Coin إلى عضو بعد تأكيد آمن", supported: true },
  { name: "leaderboard", category: "leveling", description: "أفضل الأعضاء في السيرفر", supported: true },
  { name: "glow", category: "general", description: "معلومات بوت Glow ورابط الداشبورد", supported: true },
  { name: "color-set", category: "general", description: "Set your color role by number", supported: true },
  { name: "colors", category: "general", description: "View available color roles", supported: true },
  { name: "get-emojis", category: "general", description: "استرجاع الإيموجيات بوضعها في الكوماند", supported: true },
  { name: "help", category: "general", description: "قائمة مساعدة البوت", supported: true },
  { name: "ping", category: "general", description: "عرض زمن استجابة البوت الحالي", supported: true },
  { name: "points-list", category: "general", description: "عرض كل النقاط", supported: true },
  { name: "rep", category: "general", description: "أعط شخصا نقطة سمعة. يمكن استخدامه مرة واحدة كل 24 ساعة", supported: false },
  { name: "roll", category: "general", description: "ارم نرد قياسي بـ 6 جوانب وأظهر النتيجة.", supported: true },
  { name: "suggest", category: "general", description: "تقديم اقتراح للسيرفر", supported: true },
  { name: "suggestion", category: "general", description: "إدارة اقتراح (موافقة، رفض، أو تنفيذ)", supported: false },
  { name: "title", category: "general", description: "عرض أو تغيير عنوان بروفايلك", supported: false },
  { name: "translate", category: "general", description: "ترجمة رسالة أو نص إلى لغة محددة.", supported: false },
  { name: "avatar", category: "info", description: "احصل على صورة مستخدم أو على صورتك", supported: true },
  { name: "banner", category: "info", description: "احصل على بانر مستخدم أو على بانرك", supported: true },
  { name: "invites", category: "info", description: "عرض معلومات دعواتك أو دعوات مستخدم آخر.", supported: true },
  { name: "profile", category: "info", description: "عرض بطاقة بروفايلك الشخصية أو لشخص آخر القابلة للتخصيص", supported: true },
  { name: "roles", category: "info", description: "احصل على قائمة رولات السيرفر وعدد الأعضاء", supported: true },
  { name: "server-avatar", category: "info", description: "عرض صورة السيرفر الحالية.", supported: true },
  { name: "server-banner", category: "info", description: "عرض بانر السيرفر الحالي.", supported: true },
  { name: "server", category: "info", description: "يعرض معلومات عن السيرفر", supported: true },
  { name: "user", category: "info", description: "عرض معلومات مثل ID وتاريخ الانضمام عنك أو عن مستخدم", supported: true },
  { name: "reset", category: "leveling", description: "إعادة تعيين نقاط XP النصية/الصوتية/الدعوات لكل الأعضاء أو لأعضاء محددين", supported: true },
  { name: "setlevel", category: "leveling", description: "تعيين ليفل لمستخدم", supported: true },
  { name: "setxp", category: "leveling", description: "تعيين XP لمستخدم", supported: true },
  { name: "rank", category: "leveling", description: "عرض بطاقة رانكك أو بطاقة شخص آخر في السيرفر", supported: true },
  { name: "top", category: "leveling", description: "عرض أعلى الأعضاء في النص أو الصوت", supported: true },
  { name: "add-emoji", category: "moderation", description: "رفع إيموجي مخصص جديد بالاسم ورابط الصورة المحددين.", supported: false },
  { name: "clear", category: "moderation", description: "تنظيف رسائل القناة", supported: true },
  { name: "hide", category: "moderation", description: "إخفاء قناة عن @everyone", supported: true },
  { name: "show", category: "moderation", description: "إظهار قناة مخفية لـ @everyone", supported: true },
  { name: "lock", category: "moderation", description: "تعطيل @everyone من إرسال الرسائل في قناة محددة", supported: true },
  { name: "unlock", category: "moderation", description: "السماح لـ @everyone بإرسال الرسائل في قناة محددة", supported: true },
  { name: "slowmode", category: "moderation", description: "تفعيل أو تعطيل Slowmode على قناة", supported: true },
  { name: "gdrop", category: "moderation", description: "بدء قيف-اواي درب", supported: false },
  { name: "gend", category: "moderation", description: "إنهاء قيف-اواي مبكرا", supported: false },
  { name: "glist", category: "moderation", description: "قائمة القيف-اواي النشطة", supported: false },
  { name: "greroll", category: "moderation", description: "إعادة سحب فائزي قيف-اواي", supported: false },
  { name: "gstart", category: "moderation", description: "بدء قيف-اواي جديد", supported: false },
  { name: "starboard force", category: "moderation", description: "فرض رسالة على ستاربورد بغض النظر عن عدد النجوم", supported: false },
  { name: "starboard unforce", category: "moderation", description: "إلغاء فرض رسالة لتعود للالتزام بالحد الأدنى", supported: false },
  { name: "starboard freeze", category: "moderation", description: "إيقاف تحديث عداد النجوم على منشور الستاربورد", supported: false },
  { name: "starboard unfreeze", category: "moderation", description: "السماح بتحديث عداد النجوم مجددا على منشور الستاربورد", supported: false },
  { name: "starboard trash", category: "moderation", description: "إزالة رسالة من الستاربورد ومنع إعادة إضافتها", supported: false },
  { name: "starboard untrash", category: "moderation", description: "إلغاء حذف رسالة لتعود قابلة للإضافة إلى الستاربورد", supported: false },
  { name: "ticket close", category: "moderation", description: "إغلاق التذكرة الحالية", supported: false },
  { name: "ticket claim", category: "moderation", description: "استلام التذكرة الحالية", supported: false },
  { name: "ticket reopen", category: "moderation", description: "إعادة فتح التذكرة المغلقة الحالية", supported: false },
  { name: "ticket add", category: "moderation", description: "إضافة مستخدم إلى التذكرة الحالية", supported: false },
  { name: "ticket remove", category: "moderation", description: "إزالة مستخدم من التذكرة الحالية", supported: false },
  { name: "ticket rename", category: "moderation", description: "إعادة تسمية قناة التذكرة الحالية", supported: false },
  { name: "ticket priority", category: "moderation", description: "تحديد أولوية التذكرة", supported: false },
  { name: "ticket unclaim", category: "moderation", description: "إلغاء استلام التذكرة الحالية", supported: false },
  { name: "ticket transfer", category: "moderation", description: "نقل التذكرة إلى تصنيف آخر", supported: false },
  { name: "ticket closerequest", category: "moderation", description: "طلب من منشئ التذكرة إغلاقها", supported: false },
  { name: "ticket escalate", category: "moderation", description: "تصعيد التذكرة إلى لوحة أخرى", supported: false },
  { name: "ticket note", category: "moderation", description: "إضافة ملاحظة طاقم إلى التذكرة", supported: false },
  { name: "ticket merge", category: "moderation", description: "دمج هذه التذكرة في أخرى", supported: false },
  { name: "ticket notifications", category: "moderation", description: "تبديل إشعارات التذكرة", supported: false },
  { name: "ban", category: "moderation", description: "حظر عضو", supported: true },
  { name: "unban-all", category: "moderation", description: "Unban all users currently banned in the server", supported: false },
  { name: "unban", category: "moderation", description: "رفع الحظر عن عضو", supported: true },
  { name: "inrole", category: "moderation", description: "Show all users with a specific role", supported: true },
  { name: "kick", category: "moderation", description: "طرد عضو", supported: true },
  { name: "move", category: "moderation", description: "نقل عضو إلى روم صوتي آخر", supported: true },
  { name: "mute-check", category: "moderation", description: "تحقق من حالة كتم مستخدم محدد", supported: true },
  { name: "mute-text", category: "moderation", description: "كتم عضو حتى لا يستطيع الكتابة في الرومات النصية", supported: false },
  { name: "unmute-text", category: "moderation", description: "إلغاء كتم عضو", supported: false },
  { name: "mute-voice", category: "moderation", description: "ميوت صوتي لعضو حتى لا يستطيع التحدث في الرومات الصوتية", supported: false },
  { name: "unmute-voice", category: "moderation", description: "إلغاء الميوت الصوتي لعضو", supported: false },
  { name: "points-reset", category: "moderation", description: "إعادة تعيين النقاط", supported: true },
  { name: "points", category: "moderation", description: "Manage the Glow Coin balance of a user", supported: true },
  { name: "rar", category: "moderation", description: "Remove all roles from a user", supported: true },
  { name: "role-multiple", category: "moderation", description: "إعطاء أو إزالة رول من أعضاء السيرفر بالجملة", supported: false },
  { name: "role", category: "moderation", description: "إدارة رول/رولات لأعضاء", supported: true },
  { name: "setnick", category: "moderation", description: "تغيير الاسم المستعار لعضو", supported: true },
  { name: "temprole", category: "moderation", description: "Assign a temporary role to a member", supported: false },
  { name: "timeout", category: "moderation", description: "إعطاء تايم اوت لعضو", supported: true },
  { name: "untimeout", category: "moderation", description: "إلغاء التايم اوت عن عضو", supported: true },
  { name: "vkick", category: "moderation", description: "طرد عضو من روم صوتي", supported: true },
  { name: "warn-add", category: "moderation", description: "تحذير عضو", supported: true },
  { name: "warn-remove", category: "moderation", description: "إزالة تحذيرات للسيرفر أو لمستخدم", supported: true },
  { name: "warnings", category: "moderation", description: "الحصول على قائمة التحذيرات للسيرفر أو لمستخدم", supported: true },
];

export const REGISTERED_COMMAND_NAMES = new Set(SLASH_COMMANDS.map((command) => command.name));
